# module_coverage.jl -- Parse all 84 Fortran reference-test input decks,
# build a module → tests map. Writes test/validation/MODULE_COVERAGE.md.
#
# Verifies that every Julia port has at least one Fortran reference test
# covering it (the bare minimum bar for the "faithful testing" framework).

using NJOY
using Printf

const TESTS_ROOT  = normpath(joinpath(@__DIR__, "..", "..", "njoy-reference", "tests"))
const OUTPUT_MD   = joinpath(@__DIR__, "MODULE_COVERAGE.md")

# Julia ports that exist in src/orchestration/modules/.
# (moder counted even though it's a tape-converter, since it's dispatched.)
const JULIA_PORTS = [:moder, :reconr, :broadr, :heatr, :thermr, :groupr,
                      :unresr, :ccccr, :errorr, :gaminr, :dtfr, :matxsr,
                      :viewr, :plotr, :acer, :leapr, :covr, :purr, :powr,
                      :wimsr, :mixr, :resxsr]

# Ports actively dispatched in run_njoy (from pipeline.jl).
const DISPATCHED = Set([:moder, :reconr, :broadr, :heatr, :thermr, :groupr,
                        :unresr, :ccccr, :errorr, :gaminr, :dtfr, :matxsr,
                        :viewr, :plotr])

function all_test_numbers()
    nums = Int[]
    for d in readdir(TESTS_ROOT)
        m = match(r"^(\d+)$", d)
        m === nothing && continue
        isfile(joinpath(TESTS_ROOT, d, "input")) && push!(nums, parse(Int, m.captures[1]))
    end
    sort(nums)
end

function modules_in_test(n::Int)
    input_path = joinpath(TESTS_ROOT, lpad(n, 2, '0'), "input")
    isfile(input_path) || return Symbol[]
    try
        deck = NJOY.parse_njoy_input(input_path)
        return unique([mc.name for mc in deck.calls])
    catch e
        return Symbol[]
    end
end

function ref_tape_units(n::Int)
    test_dir = joinpath(TESTS_ROOT, lpad(n, 2, '0'))
    isdir(test_dir) || return Int[]
    units = Int[]
    for f in readdir(test_dir)
        m = match(r"^referenceTape(\d+)$", f)
        m === nothing && continue
        push!(units, parse(Int, m.captures[1]))
    end
    sort(units)
end

function build_coverage()
    tests = all_test_numbers()

    # module → sorted vector of test numbers calling it
    coverage = Dict{Symbol, Vector{Int}}()
    # test → vector of modules
    per_test = Dict{Int, Vector{Symbol}}()
    # test → vector of reference tape units
    per_test_refs = Dict{Int, Vector{Int}}()

    for n in tests
        mods = modules_in_test(n)
        per_test[n] = mods
        per_test_refs[n] = ref_tape_units(n)
        for m in mods
            push!(get!(coverage, m, Int[]), n)
        end
    end

    (; tests, coverage, per_test, per_test_refs)
end

function write_markdown(c)
    io = IOBuffer()
    println(io, "# Module Coverage — Fortran Reference Tests")
    println(io)
    println(io, "Generated by `test/validation/module_coverage.jl`.")
    println(io)
    println(io, "For each Julia port, lists the Fortran reference tests that")
    println(io, "exercise it (parsed from `njoy-reference/tests/NN/input` decks).")
    println(io, "A test can cover multiple modules — it runs them as a chain,")
    println(io, "and `run_reference_test(N)` exercises the whole chain.")
    println(io)

    println(io, "## Summary")
    println(io)
    println(io, "| Module | Dispatched in `run_njoy`? | Covering tests (count) |")
    println(io, "|--------|---------------------------|------------------------|")
    all_mods = sort(collect(keys(c.coverage)))
    for m in all_mods
        tests = c.coverage[m]
        dispatched = m in DISPATCHED ? "✓" : (m in JULIA_PORTS ? "port exists, not dispatched" : "—")
        @printf(io, "| `%s` | %s | %d (%s) |\n", m, dispatched, length(tests),
                join(("T" * lpad(t, 2, '0') for t in tests), ", "))
    end
    println(io)

    # Ports with zero coverage
    zero_cov = [m for m in JULIA_PORTS if !haskey(c.coverage, m)]
    if !isempty(zero_cov)
        println(io, "### Julia ports with ZERO Fortran-reference coverage")
        println(io)
        println(io, "These have source files under `src/orchestration/modules/`")
        println(io, "but no test deck invokes them — the bare-minimum bar is NOT MET:")
        println(io)
        for m in zero_cov
            println(io, "  - `$m`")
        end
        println(io)
    end

    # Dispatched modules missing reference tapes
    println(io, "## Per-test detail (module chain + reference tapes)")
    println(io)
    println(io, "| Test | Modules | Reference tapes |")
    println(io, "|------|---------|-----------------|")
    for n in c.tests
        mods = c.per_test[n]
        refs = c.per_test_refs[n]
        mod_str  = isempty(mods) ? "(none)" : join(string.(mods), " → ")
        ref_str  = isempty(refs) ? "(none)" : join(["tape$u" for u in refs], ", ")
        @printf(io, "| T%02d | %s | %s |\n", n, mod_str, ref_str)
    end
    println(io)

    # Tests with NO reference tapes (can run but nothing to compare)
    no_ref = [n for n in c.tests if isempty(c.per_test_refs[n])]
    if !isempty(no_ref)
        println(io, "### Tests with no reference tapes")
        println(io)
        println(io, "These decks run but have no `referenceTape*` file — they")
        println(io, "only verify the pipeline executes without crashing:")
        println(io)
        println(io, join(["T" * lpad(n, 2, '0') for n in no_ref], ", "))
        println(io)
    end

    write(OUTPUT_MD, take!(io))
end

function print_terminal_summary(c)
    println()
    println("Module Coverage Summary")
    println(repeat("=", 60))
    all_mods = sort(collect(keys(c.coverage)))
    for m in all_mods
        tests = c.coverage[m]
        mark = m in DISPATCHED ? "✓" : (m in JULIA_PORTS ? "≈" : "?")
        @printf("  %s  %-12s  %3d tests   %s%s\n", mark, m, length(tests),
                join(("T" * lpad(t, 2, '0') for t in tests[1:min(10,end)]), ","),
                length(tests) > 10 ? ", …" : "")
    end

    zero_cov = [m for m in JULIA_PORTS if !haskey(c.coverage, m)]
    if !isempty(zero_cov)
        println()
        println("  Julia ports with ZERO coverage (bare-minimum bar NOT MET):")
        for m in zero_cov
            println("    - $m")
        end
    else
        println()
        println("  Every known Julia port has at least one covering Fortran test.")
    end

    no_ref = [n for n in c.tests if isempty(c.per_test_refs[n])]
    if !isempty(no_ref)
        println()
        @printf("  %d tests have NO reference tapes (execution-only): %s\n",
                length(no_ref), join(["T" * lpad(n, 2, '0') for n in no_ref], ", "))
    end
    println()
    println("Wrote $(OUTPUT_MD)")
end

function main()
    c = build_coverage()
    write_markdown(c)
    print_terminal_summary(c)
end

if abspath(PROGRAM_FILE) == @__FILE__
    main()
end
