# sweep_reference_tests.jl -- Run all 84 Fortran reference tests through
# `run_reference_test`, classify the outcome for every (test, reference-tape)
# pair, and write a Markdown report to reports/REFERENCE_SWEEP.md.
#
# Single Julia process, sequential — cache safety. Verbose + heartbeat per
# test so hangs are visible instantly (no subprocess kill; Ctrl-C to bail).
#
# Usage:
#   julia --project=. test/validation/sweep_reference_tests.jl           # all 84
#   julia --project=. test/validation/sweep_reference_tests.jl 1 2 3 4   # subset

using NJOY
using Printf

include(joinpath(@__DIR__, "reference_test.jl"))

const REPORT_DIR  = normpath(joinpath(@__DIR__, "..", "..", "reports"))
const REPORT_PATH = joinpath(REPORT_DIR, "REFERENCE_SWEEP.md")

function all_tests()
    nums = Int[]
    for d in readdir(TESTS_ROOT)
        m = match(r"^(\d+)$", d); m === nothing && continue
        isfile(joinpath(TESTS_ROOT, d, "input")) && push!(nums, parse(Int, m.captures[1]))
    end
    sort(nums)
end

# Assign a single status per tape result for reporting.
function tape_status_symbol(tr::NamedTuple, tolerances::Vector{Float64})
    if !tr.exists;              return :MISSING_TAPE; end
    if get(tr.tolerance_pass, tolerances[1], false); return :BIT_IDENTICAL; end
    # Walk through tolerances and record the loosest one that still passes
    for rtol in tolerances[2:end]
        if get(tr.tolerance_pass, rtol, false)
            return Symbol("PASS_", @sprintf("%.0e", rtol))
        end
    end
    return tr.compare !== nothing && !tr.compare.line_count_match ?
           :STRUCTURAL_FAIL : :DIFFS
end

function test_status_symbol(r::NamedTuple, tolerances::Vector{Float64})
    get(r, :timed_out, false)        && return :TIMEOUT
    !r.run_ok                        && return :CRASH
    isempty(r.tape_results)          && return :NO_REFERENCE
    ts = [tape_status_symbol(tr, tolerances) for tr in r.tape_results]
    all(t -> t == :BIT_IDENTICAL, ts)                    && return :BIT_IDENTICAL
    all(t -> t != :MISSING_TAPE && t != :DIFFS && t != :STRUCTURAL_FAIL, ts) &&
        return :NUMERIC_PASS
    any(t -> t == :MISSING_TAPE, ts)                     && return :MISSING_TAPE
    return :DIFFS
end

function run_sweep(nums::Vector{Int}; tolerances::Vector{Float64}=[1e-9, 1e-7, 1e-5, 1e-3],
                    clear_cache_per_test::Bool=false,
                    heartbeat_sec::Float64=10.0,
                    timeout_hard_sec::Float64=300.0)

    mkpath(REPORT_DIR)
    mkpath(joinpath(REPORT_DIR, "sweep_logs"))

    results = NamedTuple[]
    sweep_start = time()

    total = length(nums)
    @printf("\n%s SWEEP  %d tests  tolerances=%s\n",
            repeat("═", 40), total,
            "[" * join([@sprintf("%.0e", t) for t in tolerances], ", ") * "]")
    println(repeat("═", 90))

    for (idx, n) in enumerate(nums)
        test_id = @sprintf("T%02d", n)

        # Cache safety is already enforced by the "no parallel Julia" rule; each
        # test stays in-process. Per-test cache clear is only needed if an agent
        # suspects corruption — off by default.
        if clear_cache_per_test
            run(`bash -c "rm -rf ~/.julia/compiled/v1.12/NJOY*"`)
        end

        @printf("\n[%d/%d] %s …\n", idx, total, test_id)
        flush(stdout)

        local r
        try
            r = run_reference_test(n;
                                   tolerances=tolerances,
                                   verbose=true,
                                   heartbeat_sec=heartbeat_sec,
                                   timeout_hard_sec=timeout_hard_sec)
        catch ex
            msg = first(split(sprint(showerror, ex), '\n'))
            @printf("║ %s SWEEP-LEVEL CRASH: %s\n", test_id, msg)
            r = (; test=n, input="", work_dir="", run_ok=false,
                   run_error=msg, elapsed=0.0, timed_out=false,
                   tape_results=NamedTuple[], summary="CRASH: $msg",
                   all_pass=false)
        end

        push!(results, r)
    end

    sweep_elapsed = time() - sweep_start
    println(repeat("═", 90))
    @printf("Sweep complete: %.1fs (%.1f min)\n", sweep_elapsed, sweep_elapsed/60)

    write_report(results, tolerances, sweep_elapsed)
    print_terminal_summary(results, tolerances)
    results
end

function write_report(results, tolerances::Vector{Float64}, sweep_elapsed::Float64)
    io = IOBuffer()
    println(io, "# Reference-Test Sweep — Julia vs Fortran NJOY2016")
    println(io)
    println(io, "Generated by `test/validation/sweep_reference_tests.jl`.")
    println(io)
    println(io, "For each Fortran reference test, runs `run_njoy(…/tests/NN/input)` and")
    println(io, "compares every produced `tape{U}` against the corresponding `referenceTape{U}`")
    println(io, "using `execute.py`-equivalent line semantics (date wildcarded, floats with")
    println(io, "`rtol/atol` tolerance, non-numeric residue must match).")
    println(io)
    @printf(io, "Sweep duration: **%.1fs** (%.1f min)\n", sweep_elapsed, sweep_elapsed/60)
    println(io)

    # Counts
    status_counts = Dict{Symbol,Int}()
    for r in results
        s = test_status_symbol(r, tolerances)
        status_counts[s] = get(status_counts, s, 0) + 1
    end

    println(io, "## Summary")
    println(io)
    println(io, "| Status | Count |")
    println(io, "|--------|-------|")
    for s in [:BIT_IDENTICAL, :NUMERIC_PASS, :DIFFS, :STRUCTURAL_FAIL, :MISSING_TAPE, :NO_REFERENCE, :CRASH, :TIMEOUT]
        @printf(io, "| `%s` | %d |\n", s, get(status_counts, s, 0))
    end
    @printf(io, "| **Total** | **%d** |\n", length(results))
    println(io)

    # Per-test table
    println(io, "## Per-test results")
    println(io)
    ref_hdr = join(["`$(rtol)`" for rtol in tolerances], " / ")
    println(io, "Per-tape pass at each tolerance: ", ref_hdr)
    println(io)
    println(io, "| Test | Status | Run | Time | Reference tape results |")
    println(io, "|------|--------|-----|------|------------------------|")

    for r in results
        test_id = @sprintf("T%02d", r.test)
        status  = test_status_symbol(r, tolerances)

        run_col = r.run_ok ? "ok" : (get(r, :timed_out, false) ? "TIMEOUT" : "CRASH")

        if isempty(r.tape_results)
            tape_col = r.run_ok ? "no referenceTape*" : "—"
        else
            parts = String[]
            for tr in r.tape_results
                if !tr.exists
                    push!(parts, @sprintf("tape%d:MISSING", tr.unit))
                    continue
                end
                passes = [tr.tolerance_pass[t] ? "✓" : "✗" for t in tolerances]
                @printf("%s", "")  # no-op; keeps closure sane
                pct = tr.compare === nothing ? "" :
                      @sprintf("%d/%d", tr.compare.n_pass, tr.compare.n_cmp)
                push!(parts, @sprintf("tape%d:%s %s", tr.unit, join(passes, "/"), pct))
            end
            tape_col = join(parts, " · ")
        end

        @printf(io, "| %s | `%s` | %s | %.1fs | %s |\n", test_id, status, run_col, r.elapsed, tape_col)
    end
    println(io)

    # Crash / timeout details
    bad = [r for r in results if !r.run_ok]
    if !isempty(bad)
        println(io, "## Crashes and timeouts")
        println(io)
        for r in bad
            label = get(r, :timed_out, false) ? "TIMEOUT" : "CRASH"
            @printf(io, "- **T%02d** [%s]: %s\n", r.test, label, r.run_error)
        end
        println(io)
    end

    # Diff details (first few lines per failing tape)
    failing = [r for r in results if r.run_ok &&
                                      any(tr -> tr.exists && !get(tr.tolerance_pass, last(tolerances), false),
                                          r.tape_results)]
    if !isempty(failing)
        println(io, "## First diff per failing tape")
        println(io)
        for r in failing
            tid = @sprintf("T%02d", r.test)
            for tr in r.tape_results
                tr.exists || continue
                get(tr.tolerance_pass, last(tolerances), false) && continue
                @printf(io, "### %s tape%d\n", tid, tr.unit)
                if tr.compare === nothing
                    println(io, "(no comparison data)")
                    continue
                end
                @printf(io, "%d/%d lines match at rtol=%.0e (%s vs %s lines).\n\n",
                        tr.compare.n_pass, tr.compare.n_cmp, first(tolerances),
                        tr.compare.n_ref, tr.compare.n_trial)
                for (ln, rf, tt) in tr.compare.diffs
                    println(io, "```")
                    @printf(io, "line %d\n  REF: %s\n  JUL: %s\n", ln,
                            length(rf) > 100 ? rf[1:100] * "…" : rf,
                            length(tt) > 100 ? tt[1:100] * "…" : tt)
                    println(io, "```")
                end
            end
        end
    end

    write(REPORT_PATH, take!(io))
    @printf("Wrote %s\n", REPORT_PATH)
end

function print_terminal_summary(results, tolerances::Vector{Float64})
    status_counts = Dict{Symbol,Int}()
    for r in results
        s = test_status_symbol(r, tolerances)
        status_counts[s] = get(status_counts, s, 0) + 1
    end
    println()
    println(repeat("═", 60))
    println("Sweep Summary")
    println(repeat("═", 60))
    for s in [:BIT_IDENTICAL, :NUMERIC_PASS, :DIFFS, :STRUCTURAL_FAIL, :MISSING_TAPE, :NO_REFERENCE, :CRASH, :TIMEOUT]
        c = get(status_counts, s, 0)
        c == 0 && continue
        @printf("  %-18s  %d\n", s, c)
    end
    @printf("  %-18s  %d\n", "TOTAL", length(results))
end

if abspath(PROGRAM_FILE) == @__FILE__
    nums = isempty(ARGS) ? all_tests() : parse.(Int, ARGS)
    run_sweep(nums)
end
